### ISSUE TITLE
Magnet link opens new instance of default settings qBittorrent every time.

### ISSUE THREAD

**Issue by junglized** [portapps/qbittorrent-portable#10]
#### Steps to reproduce this issue

1. Setup qBittorrent Portable to your liking.
2. Register with .torrent files and magnet links
2. Click Magnet link.

#### Expected behaviour

After clicking magnet link the download should be added to already opened instance of qBitorrent or open the one registered and set up with magnet links.

#### Actual behaviour

Everytime magnet link is clicked a new instance of bittorrent with default settings is being opened.

### Configuration

qBittorrent version: 4.2.5-13.
OS: Win10 Pro 64bits

**Comment by crazy-max** [comment]
@junglized Working well for me, cannot reproduce your issue. Please create a proper [bug report](https://github.com/portapps/qbittorrent-portable/issues/new?template=bug_report.md) with all relevant information (**Join the log file `log\[appname]-portable.log` to this issue.**)
